switched from str to AnyUrl in the granule model
fraymio/modis-tools pull request #25
Opened 2023-03-09 20:30 UTC by EChebelyon

## Description

This hotfix allows users to download `MOD11A2` version `061`. The tiny change is switching the pydantic model for the link to the `hdf` file from `HttpUrl` to `AnyUrl`, this allows the links to have both `s3://`, `http://` and `https://` schemas.

Closes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Next Steps
- [ ] Assign a reviewer based on the [code owner document](https://github.com/fraymio/modis_tools/blob/main/.github/CODEOWNERS).

- [ ] Once your review is approved, merge and delete the feature branch

On behalf of the Modis Tools Dev Team, thank you for your hard work! ✨

2023-03-10 13:08 UTC, jamie-sgro approved these changes
LGTM

2023-03-10 15:39 UTC, cearlefraym commented
Added issue tag to auto-close

2023-03-13 13:13 UTC, lmcindewar reviewed
Looks good, thanks for updating. One small question on naming

2023-03-13 13:13 UTC, lmcindewar commented on modis_tools/constants/urls.py
> +    MOD11A2_V061_RESOURCE: str = "data.lpdaac.earthdatacloud.nasa.gov"
Eddy, did you have a chance to test products other than MOD11A2? Just checking whether we can add this as a more general resource for v061 products

2023-03-13 15:00 UTC, cearlefraym requested changes
All working on my end, before approving I recommend updating the readme to set the version to 061. If you're okay with me adding to this PR I can take that on @EChebelyon.

2023-03-14 20:45 UTC, cearlefraym approved these changes

2023-03-15 18:37 UTC, merged