Issue 17 dev environment contrib standards
fraymio/modis-tools pull request #51
Opened 2024-07-05 21:56 UTC by iamchrisearle

## Description

Closes #17 

- Adds `pyproject.toml` and `poetry.lock` for virtual environment setup using poetry
- Adds [pre-commit hooks using ruff ](https://github.com/astral-sh/ruff-pre-commit)
- Several minor file changes from running ruff formatter
- Adds relevant documentation to readme

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Next Steps
- [ ] Assign a reviewer based on the [code owner document](https://github.com/fraymio/modis_tools/blob/main/.github/CODEOWNERS).

- [ ] Once your review is approved, merge and delete the feature branch

On behalf of the Modis Tools Dev Team, thank you for your hard work! ✨

2024-07-30 12:25 UTC, jamie-sgro commented on pyproject.toml
> +authors = ["Chris <chris.c.earle@gmail.com>"]
How bold Chris :P

2024-07-30 12:27 UTC, jamie-sgro commented on modis_tools/auth.py
> +                        Likely that username and password not found"
From https://app.clickup.com/36149938/v/dc/12f6nj-75253/12f6nj-139813 under formatting

> dont_do_this = "This is a very very very very \
                  long string"
# Outputs: "This is a very very very very long string"
do_this_instead = (
    "This is a very very "
    "long string"
)
# Outputs: "This is a very very long string"

2024-07-30 12:29 UTC, jamie-sgro commented on tests/test_models.py
I'll need a comment from you as to what this change is aiming to accomplish

2024-07-30 12:32 UTC, jamie-sgro commented on pyproject.toml
> +description = "An enivornment for modis tools to download MODIS imagery from the NASA Earthdata platform"
enivornment -> environment

2024-07-30 12:33 UTC, jamie-sgro commented on pyproject.toml
> +version = "0.1.0"
These values don't match setup.py

2024-07-30 12:33 UTC, jamie-sgro commented on pyproject.toml
I reckon we should remove this file for the reasons listed in this PR

2024-07-30 12:34 UTC, jamie-sgro commented on pyproject.toml
> +setuptools = {version = "69.2.0", markers = "python_version >= '3.12'"}
This file is missing two extras:

    extras_require={
        "test": ["pytest"],
        "gdal": ["gdal"],
    }

2024-07-30 12:35 UTC, jamie-sgro commented on README.md
> +- Alternatively, To install all production dependencies, run:
I don't think the move is to add poetry here. We deploy this as a pip installable package using requirements and setup.py. Adding anything related to poetry conflates access strategy. Specifically, the pyproject.toml created here (despite not being specifically a poetry file) will cause drift with setup.py. I recommend we remove the pyproj

2024-07-30 12:35 UTC, jamie-sgro requested changes
All looks good except for the pyproj and a string split

2024-08-28 15:18 UTC, iamchrisearle commented
> All looks good except for the pyproj and a string split

Removed poetry references -- back to you

2024-10-25 16:54 UTC, jamie-sgro approved these changes
LGTM

2024-10-25 16:54 UTC, merged